#!/bin/bash


# check for root privileges
#
if [[ $EUID != 0 ]]; then
	echo "This tool requires root privileges. Try again with \"sudo \" please ..." >&2
	exit 1
fi


#
# load functions, local first
#
OPILIB=/usr/local/sbin/opi_config_libs

source ${OPILIB}/jobs.sh;
source ${OPILIB}/submenu.sh;
source ${OPILIB}/functions.sh;
source ${OPILIB}/functions-network.sh;

# collect info
main "$@"

#
# Main menu
#
while true
do
	LIST=()
	LIST+=( "System" "System and security settings" )
	LIST+=( "Network" "Wired, wireless, Bluetooth, access point" )
	LIST+=( "Personal" "Timezone, language, hostname" )
	LIST+=( "Software" "System and 3rd party software install" )
	LIST+=( "Help" "Documentation, support, sources" )

	# count number of menu items to adjust window size
	LISTLENGTH="$((12+${#LIST[@]}/2))"
	BOXLENGTH=${#LIST[@]}
	MENUTITLE="Configure \Z1$DISTRO $DISTROID\Z0 for the \Z1${BOARD_NAME}\Z0"
	# read cpu speed
	POLICY="policy0"
	[[ $(grep -c '^processor' /proc/cpuinfo) -gt 4 ]] && POLICY="policy4"
	[[ ! -d /sys/devices/system/cpu/cpufreq/policy4 ]] && POLICY="policy0"

	num=$(cat /sys/devices/system/cpu/cpufreq/$POLICY/scaling_min_freq 2> /dev/null)
		if [[ ! -z "${num##*[!0-9]*}" ]]; then
		LISTLENGTH=$((LISTLENGTH + 2))
		MIN_CPU=$(($(cat /sys/devices/system/cpu/cpufreq/$POLICY/scaling_min_freq) / 1000))
		MAX_CPU=$(($(cat /sys/devices/system/cpu/cpufreq/$POLICY/scaling_max_freq) / 1000))
		GOVERNOR_CPU=$(cat /sys/devices/system/cpu/cpufreq/$POLICY/scaling_governor)
		FREQENCIES="\nSoC runs between \Z1${MIN_CPU}\Z0 and \Z1${MAX_CPU} MHz\Z0 using \Z1${GOVERNOR_CPU}\Z0 governor.\n"
	fi
	
	# main dialog routine
	DIALOG_CANCEL=1
	DIALOG_ESC=255
	TITLELENGTH=${#MENUTITLE}

	[[ "$TITLELENGTH" -lt 60 ]] && TITLELENGTH="60"
	
	exec 3>&1
	selection=$(dialog --colors --backtitle "$BACKTITLE" --title " opi-config " --clear \
	--cancel-label "Exit" --menu "\n$MENUTITLE \n$FREQENCIES\nSupport: \Z1https://http://www.orangepi.cn/\Z0\n " \
	$LISTLENGTH ${TITLELENGTH} $BOXLENGTH "${LIST[@]}" 2>&1 1>&3)
	exit_status=$?
	exec 3>&-

	[[ $exit_status == $DIALOG_CANCEL || $exit_status == $DIALOG_ESC ]] && clear && exit

#	dialog --backtitle "$BACKTITLE" --title "Please wait" --infobox \
#	"\nLoading ${selection,,} submodule ... " 5 $((26+${#selection}))

	case $selection in
		"System" )
			submenu_settings
		;;

		"Network" )
			submenu_networking
		;;

		"Personal" )
			submenu_personal
		;;

		"Software" )
			submenu_software
		;;

		"Help" )
			t="This tool provides a straightforward way of configuring."
			t=$t"\n \nAlthough it can be run at any time, some of the"
			t=$t" options may have difficulties if you alter system settings manually.\n"
			t=$t"\n\n\Z1Support:\Z0           http://www.orangepi.cn/\n"
			t=$t"\n\Z1Sources:\Z0           https://github.com/orangepi-xunlong"
			show_box "Info" "$t" "18"
		;;
	esac

done
