#!/bin/bash

. /etc/os-release

HOSTNAME=`hostname`

# AllWinner H6
if [ ${HOSTNAME} = 'orangepi3' ];then
	BOARDNAME="Orange Pi 3"
elif [ ${HOSTNAME} = 'orangepilite2' ];then
	BOARDNAME="OPi Lite 2"
elif [ ${HOSTNAME} = 'orangepioneplus' ];then
	BOARDNAME="OPi One Plus"
# AllWinner H5
elif [ ${HOSTNAME} = 'orangepipc2' ];then
	BOARDNAME="OPi PC 2"
elif [ ${HOSTNAME} = 'orangepiprime' ];then
	BOARDNAME="OPi Prime"
elif [ ${HOSTNAME} = 'orangepizeroplus' ];then
	BOARDNAME="OPi Zero Plus"
elif [ ${HOSTNAME} = 'orangepizeroplus2h5' ];then
	BOARDNAME="OPi Zero Plus 2"
# Allwinner A64
elif [ ${HOSTNAME} = 'orangepiwin' ];then
	BOARDNAME="Orange Pi Win"
# Allwinner H2+
elif [ ${HOSTNAME} = 'orangepir1' ];then
        BOARDNAME="Orange Pi R1"
elif [ ${HOSTNAME} = 'orangepizero' ];then
        BOARDNAME="Orange Pi Zero"
# Allwinner H3
elif [ ${HOSTNAME} = 'orangepi2' ];then
        BOARDNAME="Orange Pi 2"
elif [ ${HOSTNAME} = 'orangepipc' ];then
        BOARDNAME="Orange Pi Pc"
elif [ ${HOSTNAME} = 'orangepione' ];then
        BOARDNAME="Orange Pi One"
elif [ ${HOSTNAME} = 'orangepilite' ];then
        BOARDNAME="Orange Pi Lite"
elif [ ${HOSTNAME} = 'orangepipcplus' ];then
        BOARDNAME="OPi Pc Plus"
elif [ ${HOSTNAME} = 'orangepiplus' ];then
        BOARDNAME="Orange Pi Plus"
elif [ ${HOSTNAME} = 'orangepiplus2e' ];then
        BOARDNAME="OPi Plus 2E"
elif [ ${HOSTNAME} = 'orangepizeroplus2h3' ];then
        BOARDNAME="OPi Zero Plus 2"
fi

KERNELID=$(uname -r)

toilet -f standard  -F metal ${BOARDNAME}
echo -e "\nWelcome to \e[0;91m${NAME} \x1B[0m$(if [[ $ID=ubuntu ]]; then echo ${UBUNTU_CODENAME^}; fi) with \e[0;91mLinux $KERNELID\x1B[0m\n"
