#!/bin/bash

. /etc/os-release

HOSTNAME=`hostname`

if [ ${HOSTNAME} = 'orangepi3' ];then
	BOARDNAME="Orange Pi 3"
elif [ ${HOSTNAME} = 'orangepilite2' ];then
	BOARDNAME="OPi Lite 2"
elif [ ${HOSTNAME} = 'orangepioneplus' ];then
	BOARDNAME="OPi One Plus"
fi

KERNELID=$(uname -r)

toilet -f standard  -F metal ${BOARDNAME}
echo -e "Welcome to \e[0;91m${NAME} \x1B[0m$(if [[ $ID=ubuntu ]]; then echo ${UBUNTU_CODENAME^}; fi) with \e[0;91mLinux $KERNELID\x1B[0m\n"
